name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    name: Build Linux version
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --profile release
      working-directory: ./rust
    - uses: actions/upload-artifact@v4
      with:
        name: linux build
        path: ./target/release/libgodot_mapgen.so

    

  build_windows:
    name: Build Windows version
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --profile release
      working-directory: ./rust
    - uses: actions/upload-artifact@v4
    - uses: actions/upload-artifact@v4
      with:
        name: windows build
        path: ./target/release/godot_mapgen.dll


  build_macos:
    name: Build macos version
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --profile release
      working-directory: ./rust
    - uses: actions/upload-artifact@v4
      with:
        name: macos build
        path: ./target/release/libgodot_mapgen.dylib
